theme = "modus_operandi"

[editor]
line-number = "relative"
jump-label-alphabet = "tnseriaodhgmblpufycvkwxzjq"
rulers = [80, 100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]

[editor.inline-diagnostics]
cursor-line = "hint"

[keys.normal]
"ret" = "goto_word"
