theme = "modus_operandi"

[editor]
line-number = "relative"
jump-label-alphabet = "tnseriaodhgmblpufycvkwxzjq"
rulers = [80, 100]
auto-format = true

[editor.cursor-shape]
insert = "bar"

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "read-only-indicator", "file-modification-indicator"]

[keys.normal]
"ret" = "goto_word"
