theme = "modus_operandi"

[editor]
line-number = "relative"
jump-label-alphabet = "tnseriaodhgmblpufycvkwxzjq"
rulers = [80, 100]

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.auto-save]
focus-lost  = true

[keys.normal]
"ret" = "goto_word"
