[[language]]
name = "c"
formatter = { command = "clang-format", args = ["--style=file"] }
auto-format = true
rulers = [80, 100]

[[language]]
name = "devicetree"
injection-regex = "(dtsi?|devicetree|fdt)"
file-types = ["dts", "dtsi", "overlay"]
